language: java
jdk: oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: OMvJTx6UtiLSo6uji++1xHLsn7Nyzw7ets0f1aCZI+ZMmjVd+Q5NyZ1wXVgNhXMLQQoKGiFS2ZhNaVi6z7s/Hf9AnAYwJKdYKm4KWjnVJoqFYykobfk1/2+ReN31TMn+bh99/dJAcU9jld5ozfGI0Lq8rTGINP6yHEhlSZ7G2pdo6TLM0/vgXCT/L0WTG02hz+wmloba/K7FjmJvuOsErtJtmCvwnz2MhpBFx+KTnh01WhbQB+bSqI/UGckwqKiJYeGNpgkgkuuvmd017s2ZVxdtBJTZLi6s7alFlkCsvvnQyfJt6RFqI01j1dR0VNnzRKv/in4qhl8eNrZWyoO1vj9l+gxT7ApqtL03t0Btqbf1s/mQDnhJBU7YkW4w6wsFrFl2i5SGtTqvxiMq2xvnNXDhsFLVhvU+QOR2+bc2OvwILuPbv1S1GDwDuO2t8xY3dOkL7qDkOac7ehMMq5Wg4YqEDjYGfzeN5AdO4kawWHFy8WQ3Ku7lZQ7jVcVPm4r5d6PS0PJdY0z5qOLMEXHUSsJSnlr76bntLkjwIZPdU5ETQhPispt5wdXEuzG02D1PJHM84YKnKv1T47cX79e9k4tVEEXeZZY91ImnYS1ibg550C4n/S6sPyKaQ8dQ9M86e+I2vyGRIwHtvXFyKUyE0GthG6aBqdiEGMYi2yO9PjY=
