language: java
jdk: oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: bx0mIrpkGcVXpbzxO36lg9yzOXMfJ8sGFeyG+ac6Dc2Sb4NcFkBlqt3EfXc2mVc7AjlUTbyAL1D4Rmf9ocjhchQLd/tOln2oEOhTfCxFrx4Q8xYbqsVIhHw2stDNM0Fc9toh0kR6KD0Hq5oECs/kRCM9NRTyJkzR9O3uh8yXu2kYLYzQ26Kmobkd6lkHlQrJAwENaPEaF2VMIcJMdRa1lZLXrbqy17A96ZNoysPMYKNZJEmEjMSIrL/vqAYziwJfQ0WDvMYZ8F6sVqiWkxT0vvfZNlneD3A4vFJMqeLgAECGc0/HUMr1cBlljpmRir/hi2pbxqKD/aGzIl4Ahpg8UubaEmWHY/3Le/WJ5bWngZay3h4iS5Hx4+TU++ITforv3jpxcHVbwAIWp/kqOkqybku4522AEJvVzANtTbgDbd3ezT3xgj4ypkxaHqxwKM0xXYFhx0cApG9RPfPc6LRp2+nGr0/vqTcxGyVqaGADAZe+ASv4DjrGlaWq2YrlxJuNHlkG3SYfYDftP0YKAoEg+chTDON3wOCCkW+XRXG+ENua7SYWV27ZLoLvZIMeKPoYgp21CiKZHZSGuglRUGZ+laIX+o2wBYfc+mt6taAlFX445kCdjWnE3yPS3GJFngXnkxCCYJDE0HK0DcL7zhuEhR7dmWYCtFr3Al0vYmx1xpo=
  app: ist-calculatorapi
